### ISSUE TITLE
404 Error

### ISSUE THREAD

**Issue by ryanballa** [formsort/action-heroku-deploy#2]
Hoping to get a little help figuring out why I'm seeing an error. I believe to have setup everything as the example. It deploys correctly to Heroku but fails post-deploy.

` - uses: formsort/action-heroku-deploy@v1
              with:
                  github_repo: ${{ github.repository }}
                  github_token: ${{ secrets.GH_TOKEN_FOXBOT }}
                  heroku_api_key: ${{secrets.HEROKU_API_KEY}}
                  heroku_app_name: 'foxtrot-${{ github.event.inputs.herokuEnv }}'
                  ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}
`

Here's the error:

`::set-output name=text::build_log.txt
Run release_id=$(curl -fsS 'https://api.heroku.com/apps/fs--beta/builds/10b54be7-a759-46e8-9a46-85574819adc2' \
curl: (22) The requested URL returned error: 404
Error: Process completed with exit code 22.`

**Comment by peterlada** [comment]
@ryanballa Can you please confirm that you are getting this error with the current 1.0 release? I see no way to get a heroku_app_name to be `fs--beta` in that release. I cannot repro this, please reopen if you can.
